# Case study copy for the eight Naqsh projects. pages.py turns these into project-<key>.html
CASES = [
 dict(key='rabwa', name='Rabwa Coffee', ar='ربوة', year='2025', client='Rabwa Coffee Roasters, Amman',
  services=['Brand identity', 'Packaging', 'Website'], team=['Rana Khoury', 'Karim Saleh', 'Tareq Odeh'],
  lede='A roaster on Rainbow Street had outgrown its handwritten bags. We gave it a name people could say, a mark people remember and packaging that holds a shelf.',
  brief='Rabwa had been roasting for four years under a founder\'s nickname, selling in brown paper bags labelled by hand. They were moving into supermarkets and opening two more cafés, and nobody outside Jabal Amman could find them twice.',
  approach='We kept the name and gave it a meaning: rabwa is a hill, and Amman is a city of hills. The symbol is two ridges and a rising sun, drawn to work at 12 millimetres on a sticker and three metres on a café wall. Fraunces carries the Latin, Reem Kufi the Arabic, and each origin gets its own bag colour so the shelf does the explaining.',
  stats=[('3', 'cafés opened on the new identity'), ('40', 'supermarket shelves in 2025'), ('2.4×', 'wholesale orders in the first year')],
  quote=('People used to ask for "the coffee with the brown bag". Now they ask for Rabwa.', 'Hala Mansour, founder and head roaster'),
  captions=['Primary lockup, symbol and Arabic wordmark', 'Colour and type system', 'Café system: cups, loyalty cards and stationery']),
 dict(key='aafia', name='Aafia Health', ar='عافية', year='2025', client='Aafia Family Clinics, five locations',
  services=['Identity', 'Patient app', 'Design system', 'Wayfinding'], team=['Lina Barakat', 'Maya Toukan', 'Tareq Odeh', 'Dina Hamdan'],
  lede='Five family clinics, one phone line that was always busy. We designed the brand, the booking app and the signs patients follow once they arrive.',
  brief='Aafia grew from one clinic in Khalda to five across Amman, and every one of them booked appointments by phone. Receptionists spent half their day on calls, and patients over sixty told us the old website was impossible to use.',
  approach='We started with the receptionists and forty patient interviews before drawing anything. The app does three things well: book, reschedule and see results, in Arabic or English, with type large enough to read without glasses. The same system runs the signs inside each clinic, so the colours on your phone are the colours on the wall.',
  stats=[('58%', 'of bookings now made in the app'), ('4.8', 'App Store rating'), ('31%', 'fewer calls to reception')],
  quote=('Our receptionists finally have time to look up at the patient in front of them.', 'Dr. Reem Saadeh, medical director'),
  captions=['Identity: a plus whose top arm is a leaf', 'Colour and type system, chosen for legibility', 'Wayfinding, appointment cards and app icons']),
 dict(key='mada', name='Mada Architects', ar='مدى', year='2024', client='Mada Architects, Jabal Amman',
  services=['Art direction', 'Website', 'Photography direction'], team=['Rana Khoury', 'Karim Saleh', 'Tareq Odeh'],
  lede='An eight-person practice whose houses were better than its website. We rebuilt the site around the buildings and got out of their way.',
  brief='Mada\'s work was winning competitions but its site was a template with small thumbnails and no drawings. Clients came through word of mouth, and the partners wanted a site they could send to a developer in Riyadh without apologising for it.',
  approach='We commissioned new photography of six houses and designed a site that shows each project the way an architect presents it: site, plan, then the finished rooms. The identity is deliberately quiet, a horizon line running past a frame, set in Space Grotesk with IBM Plex Sans Arabic. The drawings do the talking.',
  stats=[('6', 'projects rephotographed'), ('3×', 'longer time on project pages'), ('2', 'Gulf commissions from the new site')],
  quote=('For the first time our website looks like it was designed by architects.', 'Yara Nasrallah, partner'),
  captions=['Identity: a horizon line running past a frame', 'Colour and type system', 'Letterhead, drawings and business cards']),
 dict(key='tuleen', name='Tuleen Home', ar='تولين', year='2024', client='Tuleen Home, Sahab',
  services=['Brand identity', 'Shopify store', 'Social templates'], team=['Lina Barakat', 'Karim Saleh', 'Tareq Odeh'],
  lede='A family workshop in Sahab making solid walnut furniture, selling through Instagram DMs. We built the brand and a store that sells while they sleep.',
  brief='Tuleen had a waiting list and no website. Every order was a conversation on Instagram, prices were sent as voice notes, and customers in the Gulf could not pay without a bank transfer.',
  approach='We named the pieces after places near the workshop and built a Shopify store with made-to-order lead times, samples and delivery to the Gulf. The mark is a serif T drawn as a chair in profile. We also designed social templates the family can fill in from a phone, so new pieces reach the store and Instagram on the same day.',
  stats=[('64%', 'of orders now placed online'), ('11', 'Gulf cities shipped to'), ('0', 'voice notes about prices')],
  quote=('We make furniture. Now the website does the selling.', 'Ahmad Nsour, founder (Tuleen is his daughter)'),
  captions=['Identity: a serif T drawn as a chair in profile', 'Colour and type system', 'Social templates the team runs without a designer']),
 dict(key='sahel', name='Sahel Pantry', ar='ساحل', year='2024', client='Sahel Pantry, Jordan Valley',
  services=['Naming', 'Identity', 'Packaging'], team=['Maya Toukan', 'Rana Khoury', 'Karim Saleh'],
  lede='Olive oil, za\'atar and freekeh from Jordan Valley farms, made for shelves in Dubai and Riyadh. We named it, then designed labels that read first in Arabic.',
  brief='A group of four farming families wanted to export under one name. Their products were excellent and their labels were four different photocopies. Gulf retailers asked for a brand before they would talk about volume.',
  approach='We ran a naming workshop with the families and landed on Sahel, the plain. The labels lead with Arabic set in El Messiri, with the English underneath, because the buyers in the Gulf shop in Arabic first. Each product has its own colour and an olive branch drawn to survive being printed small on a jar lid.',
  stats=[('3', 'products at launch'), ('2', 'Gulf retailers signed'), ('4', 'farming families under one name')],
  quote=('The buyer in Dubai picked up the za\'atar jar and asked who designed it before he asked the price.', 'Nabil Abu Hamdan, export lead'),
  captions=['Name and identity: an upright olive branch', 'Colour and type system', 'Pattern, label and shipping carton']),
 dict(key='dawra', name='Dawra', ar='دورة', year='2023', client='Dawra, Amman start-up',
  services=['Product design', 'Design system', 'Launch campaign'], team=['Lina Barakat', 'Dina Hamdan', 'Tareq Odeh'],
  lede='Every family in Jordan knows the savings circle: ten people, one pot, a different winner each month. Dawra puts it in an app, and we designed it.',
  brief='The founders had a working prototype and a problem: people trusted the circle because they trusted each other, not an app. The design had to make every payment visible to every member without feeling like surveillance.',
  approach='The whole product is one idea: a ring in ten segments, one for each member. It is the logo, the home screen and the progress bar. Members see who has paid and whose turn comes next, and reminders are written like a cousin would write them. The launch posters in Amman and Irbid used the same bright lime so the app icon was recognisable before anyone downloaded it.',
  stats=[('38k', 'downloads in the first six months'), ('9,200', 'active savings circles'), ('97%', 'of monthly payments on time')],
  quote=('Users told us it finally felt like their aunt\'s savings circle, just without the arguments.', 'Omar Atallah, co-founder'),
  captions=['Identity: one ring, ten members', 'Colour and type system', 'Launch posters and app icon family']),
 dict(key='layali', name='Layali Dead Sea Resort', ar='ليالي', year='2023', client='Layali Dead Sea Resort, Sweimeh',
  services=['Brand refresh', 'Bilingual website', 'Wayfinding', 'Stationery'], team=['Rana Khoury', 'Maya Toukan', 'Karim Saleh', 'Tareq Odeh'],
  lede='A 120-room resort at Sweimeh that looked like every other resort on the shore. We moved the brand from the beach to the evening.',
  brief='Layali competed on price with four larger hotels a short drive away. Guest reviews kept mentioning the same thing: the sunsets from the terrace and the quiet after dark. The brand said neither.',
  approach='We rebuilt the identity around the name, which means nights: a crescent over the water, deep dusk blue and gold. Playfair Display in spaced capitals for the Latin, and Aref Ruqaa for the Arabic, so the signs feel written by hand. The new website sells the evenings first and the rooms second.',
  stats=[('+18%', 'direct bookings in the first year'), ('120', 'rooms and suites re-signed'), ('4.7', 'average guest rating, up from 4.2')],
  quote=('Guests now arrive talking about the sunset terrace before they have seen it.', 'Faris Haddad, general manager'),
  captions=['Identity: a crescent over three waves', 'Colour and type system', 'Wayfinding and guest stationery']),
 dict(key='fakhar', name='Fakhar Ceramics', ar='فخار', year='2022', client='Fakhar Ceramics, Madaba',
  services=['Identity', 'Packaging', 'Online shop'], team=['Karim Saleh', 'Dina Hamdan', 'Tareq Odeh'],
  lede='A two-person pottery studio in Madaba selling at weekend markets. We gave them an identity with the character of their work and a shop to sell it year-round.',
  brief='Nour and her brother make tableware by hand in a studio off King Talal Street. Their work sold out at every market, and then there was nothing to buy until the next one.',
  approach='The symbol is a thrown vessel, and the wordmark is set in Bricolage Grotesque, which is slightly irregular in the way handmade pottery is. The identity is applied with rubber stamps rather than printing, so every box is a little different. The online shop tells you who made each piece and when it came out of the kiln.',
  stats=[('70%', 'of sales now online'), ('3', 'hotels ordering tableware'), ('12', 'stamp and tape designs')],
  quote=('Our boxes get photographed more than our cups do.', 'Nour Haddadin, potter'),
  captions=['Identity: a thrown vessel, stamped not printed', 'Colour and type system', 'Pattern, stationery and wordmarks']),
]
